/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.Datos;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class frmUsuarios extends javax.swing.JInternalFrame {

      private Datos misDatos;
      private int usuAct =0;
      private boolean nuevo=false;
      
    //metodo
    public void setDatos(Datos misDatos)
    {
        this.misDatos= misDatos;
    }
    public frmUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TxtIdUsuario = new javax.swing.JTextField();
        TxtNombres = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtApellidos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtClave = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        TxtConfirmacion = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        CmbPerfil = new javax.swing.JComboBox<>();
        BtnPrimero = new javax.swing.JButton();
        BtnUltimo = new javax.swing.JButton();
        BtnAnterior = new javax.swing.JButton();
        BtnSiguiente = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Usuarios");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setText("ID Usuario :");

        TxtIdUsuario.setEnabled(false);

        TxtNombres.setEnabled(false);

        jLabel2.setText("Nombres :");

        jLabel3.setText("Apellidos :");

        TxtApellidos.setEnabled(false);

        jLabel4.setText("Clave :");

        TxtClave.setEnabled(false);

        jLabel5.setText("Confirmación :");

        TxtConfirmacion.setEnabled(false);

        jLabel6.setText("Perfil :");

        CmbPerfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione un Perfil", "Administrador", "Empleado" }));
        CmbPerfil.setEnabled(false);

        BtnPrimero.setText("Primero");

        BtnUltimo.setText("Anterior");

        BtnAnterior.setText("Siguiente");

        BtnSiguiente.setText("Ultimo");

        btnBorrar.setText("Eliminar");
        btnBorrar.setToolTipText("Elimina el registro actual");

        btnNuevo.setText("Nuevo");
        btnNuevo.setToolTipText("Crea un Nuevo Registro");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.setToolTipText("Modifica el registro Actual");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.setToolTipText("Guarda los Cambios");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnBuscar.setText("buscar");
        btnBuscar.setToolTipText("Busca el registro actual");

        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("Busca el registro actual");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(0, 51, 255));
        jLabel7.setText("*Campos obligatorios");
        jLabel7.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel3)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtApellidos)
                                .addGap(10, 10, 10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(TxtConfirmacion)
                                .addGap(10, 10, 10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(CmbPerfil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(10, 10, 10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtNombres)
                                .addGap(148, 148, 148))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 48, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(BtnPrimero)
                                .addGap(4, 4, 4)
                                .addComponent(BtnUltimo)
                                .addGap(12, 12, 12)
                                .addComponent(BtnAnterior)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(124, 124, 124))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBorrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(CmbPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TxtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(TxtConfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnPrimero)
                    .addComponent(BtnUltimo)
                    .addComponent(BtnAnterior)
                    .addComponent(BtnSiguiente))
                .addGap(10, 10, 10)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32))
        );

        jLabel1.getAccessibleContext().setAccessibleName("ID Usuario* :");
        jLabel2.getAccessibleContext().setAccessibleName("Nombres* :");
        jLabel3.getAccessibleContext().setAccessibleName("Apellidos* :");
        jLabel4.getAccessibleContext().setAccessibleName("Clave* :");
        jLabel5.getAccessibleContext().setAccessibleName("Confirmación* :");
        jLabel6.getAccessibleContext().setAccessibleName("Perfil* :");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
      //Habilitar lo botones
        BtnPrimero.setEnabled(false);
        BtnAnterior.setEnabled(false);
        BtnSiguiente.setEnabled(false);
        BtnUltimo.setEnabled(false);
        btnNuevo.setEnabled(false);
        btnModificar.setEnabled(false);
        btnBorrar.setEnabled(false);
        btnBuscar.setEnabled(false);
        btnGuardar.setEnabled(true);
        btnCancelar.setEnabled(true);
        
       //habilitar lo campos
      TxtIdUsuario.setEnabled(true);
      TxtNombres.setEnabled(true);
      TxtApellidos.setEnabled(true);
      TxtClave.setEnabled(true);
      TxtConfirmacion.setEnabled(true);
      CmbPerfil.setEnabled(true);
      
     //limpiar campos
     TxtIdUsuario.setText("");
     TxtNombres.setText("");
     TxtApellidos.setText("");
     TxtClave.setText("");
     TxtConfirmacion.setText("");
     CmbPerfil.setSelectedIndex(0);
     //activamos el flag registro nuevl
     nuevo=true;
     
      //foco al campo iD
      TxtIdUsuario.requestFocusInWindow();
      
      
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
            //validaciones
        if (TxtIdUsuario.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe digitar un ID");
            TxtIdUsuario.requestFocusInWindow();
            return;
        }
        
           if (CmbPerfil.getSelectedIndex()==0 ) {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar un perfíl.");
            CmbPerfil.requestFocusInWindow();
            return;
        }
           
           if (TxtNombres.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe digitar un nombre(s)");
            TxtNombres.requestFocusInWindow();
            return;
            }
           
           if (TxtApellidos.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe digitar un Apellido.");
            TxtApellidos.requestFocusInWindow();
            return;
            }
           
           String clave=new String(TxtClave.getPassword());
           String confirmacion=new String(TxtConfirmacion.getPassword());
           
           if (new String(TxtClave.getPassword()).equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe digitar una Clave.");
            TxtClave.requestFocusInWindow();
            return;
            }   
           
            if (new String(TxtConfirmacion.getPassword()).equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe digitar una Confirmación.");
            TxtConfirmacion.requestFocusInWindow();
            return;
            }   
            
            if (clave.equals(confirmacion)) {
                
            JOptionPane.showMessageDialog(rootPane, "La clave y la confirmación no son iguales.");
            TxtClave.requestFocusInWindow();
            return;            
            }
            
            //si el usuario no exista como validacion
           int pos =misDatos.posicionUsuario(TxtIdUsuario.getText());
            if (nuevo) {
                if (pos!=-1) {
                    JOptionPane.showMessageDialog(rootPane, "Usuario ya existe.");
                    TxtIdUsuario.requestFocusInWindow();
                    return;
                }
            } else{
                 if (pos==-1) {
                    JOptionPane.showMessageDialog(rootPane, "Usuario no existe.");
                    TxtIdUsuario.requestFocusInWindow();
                    return;                              
            }
        }
        //Dehabilitar los botones
        BtnPrimero.setEnabled(true);
        BtnAnterior.setEnabled(true);
        BtnSiguiente.setEnabled(true);
        BtnUltimo.setEnabled(true);
        btnNuevo.setEnabled(true);
        btnModificar.setEnabled(true);
        btnBorrar.setEnabled(true);
        btnBuscar.setEnabled(true);
        btnGuardar.setEnabled(false);
        btnCancelar.setEnabled(false);       
        
        //Dehabilitar lo campos
        TxtIdUsuario.setEnabled(false);
        TxtNombres.setEnabled(false);
        TxtApellidos.setEnabled(false);
        TxtClave.setEnabled(false);
        TxtConfirmacion.setEnabled(false);
        CmbPerfil.setEnabled(false);
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
         
          //Dehabilitar los botones
        BtnPrimero.setEnabled(true);
        BtnAnterior.setEnabled(true);
        BtnSiguiente.setEnabled(true);
        BtnUltimo.setEnabled(true);
        btnNuevo.setEnabled(true);
        btnModificar.setEnabled(true);
        btnBorrar.setEnabled(true);
        btnBuscar.setEnabled(true);
        btnGuardar.setEnabled(false);
        btnCancelar.setEnabled(false);       
        
        //Dehabilitar lo campos
        TxtIdUsuario.setEnabled(false);
        TxtNombres.setEnabled(false);
        TxtApellidos.setEnabled(false);
        TxtClave.setEnabled(false);
        TxtConfirmacion.setEnabled(false);
        CmbPerfil.setEnabled(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        //Habilitar lo botones
        BtnPrimero.setEnabled(false);
        BtnAnterior.setEnabled(false);
        BtnSiguiente.setEnabled(false);
        BtnUltimo.setEnabled(false);
        btnNuevo.setEnabled(false);
        btnModificar.setEnabled(false);
        btnBorrar.setEnabled(false);
        btnBuscar.setEnabled(false);
        btnGuardar.setEnabled(true);
        btnCancelar.setEnabled(true);
        
       //habilitar lo campos   
      TxtNombres.setEnabled(true);
      TxtApellidos.setEnabled(true);
      TxtClave.setEnabled(true);
      TxtConfirmacion.setEnabled(true);
      CmbPerfil.setEnabled(true);
     
        //Desactivamos el flag registro nuevl
     nuevo=false;
      //foco al campo nombres
      TxtNombres.requestFocusInWindow();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
       //click derecho event y agregar 
       TxtIdUsuario.setText(misDatos.getUsuarios()[usuAct].getIdUsuario());
       TxtNombres.setText(misDatos.getUsuarios()[usuAct].getNombres());
       TxtApellidos.setText(misDatos.getUsuarios()[usuAct].getApellidos());
       TxtClave.setText(misDatos.getUsuarios()[usuAct].getClave());
       CmbPerfil.setSelectedIndex(misDatos.getUsuarios()[usuAct].getPerfil());
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAnterior;
    private javax.swing.JButton BtnPrimero;
    private javax.swing.JButton BtnSiguiente;
    private javax.swing.JButton BtnUltimo;
    private javax.swing.JComboBox<String> CmbPerfil;
    private javax.swing.JTextField TxtApellidos;
    private javax.swing.JPasswordField TxtClave;
    private javax.swing.JPasswordField TxtConfirmacion;
    private javax.swing.JTextField TxtIdUsuario;
    private javax.swing.JTextField TxtNombres;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
